# Option 1: GitHub Actions + Twitter API (Free Tier - 1500 posts/month)
# You can use Twitter's free API tier which allows 1,500 posts per month
# Perfect for daily follower updates (30 posts/month)

# .github/workflows/follower-tracker.yml
name: Twitter Follower Tracker

on:
  schedule:
    # Run every day at 7 PM IST (1:30 PM UTC)
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  track-followers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 tweepy
    
    - name: Track followers and tweet
      run: python track_and_tweet.py
      env:
        TARGET_USERNAME: ${{ vars.TARGET_USERNAME }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add follower_data.json
        git commit -m "Update follower data - $(date)" || exit 0
        git push
